spring.application.name=PosBarLacteo

# IMPRESCINDIBLE PARA RENDER: Asigna el puerto dinámico de Render (o 8080 en local)
server.port=${PORT:8080}

# Base de datos (Usa MySQL local por defecto si no hay variable)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tu_base_local?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu_password_local}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# API Facturación (Haulmer)
facturacion.api.url=${FACTURACION_API_URL:https://dev-api.haulmer.com}
facturacion.api.key=${FACTURACION_API_KEY}

# Mercado Pago
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}

# Credenciales Flow
flow.api.key=${FLOW_API_KEY}
flow.secret.key=${FLOW_SECRET_KEY}

# La URL de tu React alojado (Vercel o dominio propio)
app.frontend.url=https://www.kipipos.cl

# La URL PÚBLICA donde está alojado tu Spring Boot (es crucial que Flow pueda llegar aquí)
app.backend.url=https://kipiweb-backend.onrender.com


#para local:

#app.frontend.url=http://localhost:5173
#app.backend.url=http://localhost:8080