spring.application.name=PosBarLacteo

# Cambiamos el endpoint de AWS por localhost como valor por defecto
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://tramway.proxy.rlwy.net:43917/railway?useSSL=false&serverTimezone=UTC}
# Aquí pones tu usuario local (usualmente root)
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

# IMPORTANTE: Reemplaza 'tu_password_local' por la clave que le pusiste a tu MySQL local
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YDJkAxWxcZnOrxMqsiLBGKJJPvLJrOza}

# Para que Hibernate cree las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ---------------------------------------------------------
# CREDENCIALES API FACTURACIÓN (HAULMER SANDBOX)
# ---------------------------------------------------------
facturacion.api.url=https://dev-api.haulmer.com
facturacion.api.key=928e15a2d14d4a6292345f04960f4bd3


spring.jpa.properties.hibernate.default_batch_fetch_size=100

mercadopago.access.token=APP_USR-1077483203874370-070620-a43e79124f2924d4fa2690b683e77143-3522374115

# Credenciales de integración Flow (Sandbox o Producción)
flow.api.key=1F00BD54-7B84-43DE-B617-2ALCEA40ECE7
flow.secret.key=f7847f29456c3aff42a75b9340c1a7f26095d365